### ISSUE TITLE
关于 BikeNYC 数据集的使用

### ISSUE THREAD

**Issue by hczs** [pengzhangzhi/spatial-temporal-transformer#2]
你好，BikeNYC 数据集的 prepare 和 train 没有在 readme 中给出使用说明，自己运行的话，也不知道如何确定 BikeNYC.json 如何配置，麻烦作者给出运行方法，感谢！

**Comment by pengzhangzhi** [comment]
您好，就用默认的设置就行啦！运行时遇到什么问题可以post上来
